/**
 * Интерфейс для менеджера палитр
 */
import type {
  Hex,
  InterfacePalette,
  SyntaxPalette,
  RichSyntaxPalette,
} from '../../types/theme'

export interface IPaletteManager {
  // Доступ к палитрам
  getInterfacePalette(): InterfacePalette
  getSyntaxPalette(): SyntaxPalette
  getRichSyntaxPalette(): RichSyntaxPalette

  // Модификация палитр
  updateInterfacePalette(updates: Partial<InterfacePalette>): void
  updateSyntaxPalette(updates: Partial<SyntaxPalette>): void
  updateRichSyntaxPalette(updates: Partial<RichSyntaxPalette>): void

  // Валидация
  validatePalette(
    palette: Partial<InterfacePalette | SyntaxPalette | RichSyntaxPalette>
  ): boolean
  getValidationErrors(): string[]

  // Экспорт/импорт
  exportPalette(): string
  importPalette(data: string): boolean

  // Генерация производных цветов
  generateDerivedColors(): void
  optimizeForAccessibility(): void
}

export interface PaletteConfig {
  enableValidation?: boolean
  strictMode?: boolean
  autoGenerateDerived?: boolean
  optimizeOnUpdate?: boolean
}
